# Generated by Django 3.2.18 on 2023-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
