# Generated by Django 3.2.18 on 2023-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(default='Basic', max_length=200),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
